### ISSUE TITLE
Repo transfer

### ISSUE THREAD

**Issue by strdr4605** [lindelof/awesome-interesting-react#1]
Hi @lindelof, I received an mail that you want to transfer this repo to my account. You created several nice packages/projects. Not like I don't need it, but I just wanted to know why would you like to give me the ownership?! 

Also, what is the difference between this repo and https://github.com/enaqx/awesome-react?
Did you try to submit react-mouse-particles, particles-bg, react-nice-resume to https://github.com/enaqx/awesome-react?

To not communicate over issues you can send me a mail at str.dr4605@gmail.com

**Comment by lindelof** [comment]
Oh thank you very much
